codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  range: 70..100
  precision: 2
  round: down
  ignore:
    - "tests/**"
    - "**/_version.py"
    - "**/__init__.py"

status:
  project: # overall coverage
    default:
      informational: true
      target: auto # fail on any drop
      threshold: 0% # or 0.5 % if you want slack
  patch: # changed lines
    default:
      informational: true
      target: 97%

comment:
  layout: header, changes, diff
  behavior: default
  require_changes: false
  branches: null
  flags: null
  paths: null

ignore:
  - "tests"
  - "**/_version.py"
  - "**/__init__.py"
