name: Check safety

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  safety:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3.4.0
      - name: Security vulnerabilities scan
        uses: aufdenpunkt/python-safety-check@v1.0.5
        with:
          scan_requirements_file_only: "true"
