name: Check safety

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  safety:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3.4.0
      - name: Write setup.py install_requires into requirements.txt
        run: |
          python .github/workflows/install_requires_to_requirements.py "$PWD/setup.py" "$PWD/requirements.txt"
          cat requirements.txt

      - name: Security vulnerabilities scan
        uses: aufdenpunkt/python-safety-check@v1.0.5
        with:
          scan_requirements_file_only: "true"
